AWSTemplateFormatVersion: 2010-09-09

Resources:

    kms:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-kms.yml

    s3:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: [kms]
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-s3.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmss3

    iam:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - kms
            - s3
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-iam.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmsarn
                Bucketdataconsume: !GetAtt s3.Outputs.Bucketdata

    lambdas:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: iam
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-lambdas.yml
            Parameters:
                LambdaExecutionRole: !GetAtt iam.Outputs.LambdaExecutionRolearn

    glue:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - iam
            - s3
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-glue.yaml
            Parameters:
                roleglue: !GetAtt iam.Outputs.glueExecutionRolearn

    step:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - iam
            - lambda
            - glue
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-step.yaml
            Parameters:
                roleglue: !GetAtt iam.Outputs.stepExecutionRolearn


