AWSTemplateFormatVersion: 2010-09-09
Parameters:
    S3KMSKey:
        Description: Nombre
        Type: String
     
Resources:

    kms:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://infra-poc1-etl-serverless.s3.us-east-1.amazonaws.com/template-kms.yaml

    s3:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://infra-poc1-etl-serverless.s3.us-east-1.amazonaws.com/template-s3.yaml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmss3

    iam:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: kms,s3
        Properties:
            TemplateURL: https://infra-poc1-etl-serverless.s3.us-east-1.amazonaws.com/template-iam.yaml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmss3  

    lambdas:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: iam
        Properties:
            TemplateURL: https://infra-poc1-etl-serverless.s3.us-east-1.amazonaws.com/template-lambdas.yaml
    


