AWSTemplateFormatVersion: 2010-09-09

Resources:

    kms:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-kms.yml

    s3:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: [kms]
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-s3.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmss3

    iam:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: 
            - kms
            - s3
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-iam.yml
            Parameters:
                S3KMSKey: !GetAtt kms.Outputs.kmsarn

    lambdas:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: iam
        Properties:
            TemplateURL: https://aw1289001-public-bucket.s3.us-east-1.amazonaws.com/template-lambdas.yml
            Parameters:
                LambdaExecutionRole: !GetAtt iam.Outputs.LambdaExecutionRolearn


