AWSTemplateFormatVersion: '2010-09-09'
Description: lambdas.

Parameters:
    LambdaExecutionRole:
        Type: String

Resources:
  LambdaFunction1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Extract_API_COVID_USA
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: s3_lambda_code
        S3Key: lambda_function_COL.zip
      Timeout: 120
      MemorySize: 128

  LambdaFunction2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Extract_API_COVID_COL
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: s3_lambda_code
        S3Key: lambda_function_USA.zip
      Timeout: 120
      MemorySize: 128