AWSTemplateFormatVersion: '2010-09-09'
Description: iam roles.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3_raw_data
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref S3KMSKey