AWSTemplateFormatVersion: '2010-09-09'
Description: iam roles.

Resources:
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key para encriptar objetos en el bucket S3
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource:
              - !Sub arn:aws:s3:::s3_raw_data
              - !Sub arn:aws:s3:::s3_lambda_code

Outputs:
  kmss3:
      Value: !Ref S3KMSKey
      Export:
        Name: kmss3
  kmsarn:
      Value: !GetAtt S3KMSKey.Arn
      Export:
        Name: kmsarn